CREATE TABLE modules (
    id int AUTO_INCREMENT,
    name varchar(255),
    PRIMARY KEY (id)
);

INSERT INTO modules (name)
VALUES
("3D Modelling and Animation"),
("AI, Culture and Society"),
("Aboriginal Law"),
("Academic Communication for International Relations 1"),
("Academic Communication for International Relations 2"),
("Academic Development for Arts and Humanities 1"),
("Academic Development for Arts and Humanities 2"),
("Academic Development for Business and Economics 1"),
("Academic Development for Business and Economics 2"),
("Academic Development for Psychology 1"),
("Academic Development for Psychology 2"),
("Academic Development for Social Sciences 1"),
("Academic Development for Social Sciences 2"),
("Academic Skills in Life Sciences"),
("Accounting for Decision Makers"),
("Accounting for Managers"),
("Acquired Intelligence & Adaptive Behaviour"),
("Activism, Development and Violence: Global Systems, Local Encounters"),
("Acts of Writing 1"),
("Acts of Writing 2"),
("Adaptive Systems"),
("Adult Family Law"),
("Advanced Audit and Assurance"),
("Advanced Composition Portfolio"),
("Advanced Condensed State Physics"),
("Advanced Contract Law in Practice (Spr)"),
("Advanced Coordination and Main Group Chemistry"),
("Advanced Cosmology"),
("Advanced Digital Signal Processing"),
("Advanced Electronic Systems"),
("Advanced Financial Accounting"),
("Advanced Haematology and Transfusion Science"),
("Advanced Issues in Employment Law"),
("Advanced Macroeconomics"),
("Advanced Management Accounting"),
("Advanced Manufacturing Technologies"),
("Advanced Methods in Molecular Research"),
("Advanced Microeconomics"),
("Advanced Nanoscience and Molecular Structure"),
("Advanced Natural Language Engineering"),
("Advanced Numerical Analysis (L.6)"),
("Advanced Numerical Analysis (L.7)"),
("Advanced Partial Differential Equations (L.6)"),
("Advanced Partial Differential Equations (L.7)"),
("Advanced Performance"),
("Advanced Physics Laboratory A"),
("Advanced Physics Laboratory B"),
("Advanced Screenwriting"),
("Advanced Software Engineering"),
("Advanced Spectroscopy"),
("Advanced Synthetic Methods"),
("Advanced Taxation (UK)"),
("Advanced Techniques in Neuroscience"),
("Advanced Technology Automotive Systems"),
("Advanced Thermofluids"),
("Advanced Topics in Control of Electromechanical Systems"),
("Advanced Topics in Discourse and Interaction"),
("Advanced Topics in Environmental Law"),
("Advanced Topics in Language Structure, Variation and Change"),
("Advanced Topics in Psychology"),
("Advanced Turbomachinery"),
("Advances in Climate Sciences"),
("Advertising (E)"),
("Aesthetics"),
("African Zoology Field Course"),
("Algebra"),
("Alternative Dispute Resolution"),
("Alternative Investment Funds"),
("Alternative Societies (Spr)"),
("America in the 21st Century"),
("American Cities"),
("American Identities"),
("American Literature in the Long Twentieth Century"),
("American Mandatory Year Abroad - American Studies"),
("American Political Culture"),
("American Popular Music"),
("American Studies Dissertation"),
("American Teen Cinema: Coming of Age on Screen"),
("Analogue Communication and Propagation"),
("Analysing Film"),
("Analysing Film B"),
("Analysing Media, Film and Music"),
("Analysing data"),
("Analysis 1"),
("Analysis 2"),
("Ancient Philosophy"),
("Animal Behavioural Ecology"),
("Animal-Plant Interactions"),
("Animals and Screen Media"),
("Anthropology Thesis"),
("Anthropology in the World: Theory, Knowledge, Action (and back again)"),
("Anthropology of the Body"),
("Applications of Organic and Bioinorganic Chemistry"),
("Applied Econometrics"),
("Applied Economics Dissertation"),
("Applied Finance Project"),
("Applied Human Virology and Bacteriology"),
("Applied Mathematics for Economists"),
("Applied Research I: Project Design"),
("Applied Research II: Final Project"),
("Applied Skills in Biology"),
("Applied Skills in Chemistry"),
("Applied Statistics for Finance and Economics"),
("Applied Technology"),
("Applied Technology for Product Design"),
("Applying Physics Skills"),
("Applying Psychology to Everyday Problems"),
("Approaches to Contemporary Performance"),
("Approaches to Discourse"),
("Approaching Drama, Theatre and Performance"),
("Arabic Ab initio A"),
("Arabic Ab initio B"),
("Arabic Advanced A"),
("Arabic Advanced B"),
("Arabic Intermediate A"),
("Arabic Intermediate B"),
("Arabic in Context A"),
("Arranging for Songs and Ensembles"),
("Art and Place: Sites, Spaces and Identities"),
("Art and the City I"),
("Art and the City II"),
("Art on Site: Place, Identity, Meaning"),
("Arts and Lifestyle Journalism"),
("Aspects of Commercial Law"),
("Astrophysical Processes"),
("Asymmetric Synthesis and Catalysis"),
("Atmospheres and Interfaces"),
("Atom Light Interactions"),
("Atomic Physics"),
("Attention: Distraction, daydreaming and diversity"),
("Audio and Podcasting Journalism"),
("Audiovisual Journalism"),
("Audiovisual Practices"),
("Audit and Assurance"),
("Autism Across the Lifespan"),
("Autonomous Vehicles"),
("BA Dissertation (International Relations)"),
("BSc Final Year Project"),
("Becoming a Researcher"),
("Becoming a Researcher - Theories and Methods"),
("Behavioural Economics"),
("Beyond the Standard Model"),
("Bio-organic Chemistry"),
("Biochemistry Industrial Placement"),
("Biological Chemistry"),
("Biological Psychology"),
("Biological Psychology of Mental Health"),
("Black Lives Matter: Postcolonial and Decolonial Representations"),
("Blockchains and Crypto Assets"),
("Bonding and Spectroscopy"),
("Box Set TV: Contemporary Serial Television"),
("Brain and Behaviour"),
("British Cinema A"),
("British Cinema B"),
("British Political History"),
("British Sign Language and Deaf Culture 1A"),
("British Sign Language and Deaf Culture 1B"),
("British Sign Language and Deaf Culture 2A"),
("British Sign Language and Deaf Culture 2B"),
("British Sign Language and Deaf Culture 3A"),
("British Sign Language and Deaf Culture 3B"),
("Business Law and Practice"),
("Business Management Case Study"),
("Business Strategy Report"),
("Business and Project Management"),
("Business in Action"),
("Business in Society"),
("Business-to-Business Marketing Management"),
("Calculus of Several Variables"),
("Canadian Administrative Law"),
("Canadian Constitutional Law"),
("Canadian Constitutional Law in Comparative Perspective Advanced"),
("Capital Culture: Money, Commerce and Writing"),
("Capitalism and Geopolitics"),
("Carceral Technologies"),
("Caring and Helping: the Psychology of Concern and Commitment"),
("Celebrity, Media and Culture"),
("Cell Biology"),
("Cell Regulation and Cancer"),
("Cell Signalling and its Applications in Therapeutics and Disease"),
("Championing Literacy Placement"),
("Chemical Principles"),
("Chemistry Advanced Project (MChem)"),
("Chemistry Industrial Project"),
("Chemistry Project (Year 3)"),
("Chemistry of the p-Block and f-Block Elements"),
("Chemistry of the p-Block and f-Block Elements - E-Learning"),
("Child Language Acquisition"),
("Child Language: Development, Disorders and Individual Differences"),
("Child Law"),
("Children's Rights and Legal Frameworks"),
("Chinese Ab initio A"),
("Chinese Ab initio B"),
("Chinese Advanced A"),
("Chinese Advanced B"),
("Chinese Cinema"),
("Chinese Intermediate A"),
("Chinese Intermediate B"),
("Chinese in Context A"),
("Chinese in Context B"),
("Cinema and Migration"),
("Cinema and Sexualities"),
("Cities and Urban Lives"),
("Class, Community and Nation Through the Pandemic Portal"),
("Class, Culture & Conflict: A View from The Inside"),
("Class, Culture and Contemporary Writing"),
("Classical Political Theory & International Relations"),
("Classical Sociological Theory"),
("Climate Change Economics"),
("Climate Finance"),
("Clinical Biochemistry"),
("Clinical Legal Education"),
("Clinical Psychology and Mental Health"),
("Clinical Psychology in Practice"),
("Co-ordination Chemistry"),
("Coastal Biology and Ecology Field Course"),
("Cognition in Clinical Contexts"),
("Cognitive Neuroscience"),
("Cognitive Psychology"),
("Colonialism and After"),
("Colonialism and Modern Social Theory"),
("Combating Disease"),
("Commercial Sales Law"),
("Communicating Politics"),
("Communicating STEM"),
("Communicating STEM for Life Sciences"),
("Communication Design"),
("Communication and Learning Skills"),
("Company Law 1"),
("Company Law 2"),
("Comparative Animal Physiology and Morphology"),
("Comparative Programming"),
("Comparative Psychology: The Psychology of Animal Behaviour"),
("Comparative Public Policy"),
("Competition Law and Markets"),
("Competition Law: International Perspectives"),
("Compilers and Computer Architecture"),
("Computational Aesthetics"),
("Computational Chemistry"),
("Computational Fluid Dynamics"),
("Computational Mathematics"),
("Computer Aided Visualisation"),
("Computer Networks"),
("Computer Vision"),
("Computing Project"),
("Computing for Life Sciences"),
("Conflict & Cooperation in Social Groups"),
("Conscious and Unconscious Mental Processes"),
("Conservation Biology I"),
("Conservation Biology II"),
("Conservation Ecology Field Course"),
("Conservation in Practice"),
("Constitutional Foundations of the European Union"),
("Consumer Behaviour"),
("Contemporary Economic Issues"),
("Contemporary International Theory"),
("Contemporary Issues in Accounting"),
("Contemporary Issues in Healthcare Law"),
("Contemporary Issues in Politics"),
("Contemporary Literature and Culture"),
("Contemporary Stylistics: The discourse of film and drama"),
("Contemporary Topics in Child Development and Wellbeing"),
("Contexts of Social Work"),
("Continuum Mechanics"),
("Contract Law 1"),
("Contract Law 2"),
("Contract Law Advanced 1"),
("Contract Law Advanced 2"),
("Control Engineering"),
("Coral Reef Ecology Field Course"),
("Coral Reef Ecology Field Course (Masters)"),
("Corporate Governance and Ethics"),
("Corporate Social Responsibility, Sustainability and Business Ethics"),
("Corporate and International Finance"),
("Cosmology"),
("Cradle to the Grave A: welfare and wellbeing across the lifecourse"),
("Cradle to the Grave B: Welfare and Wellbeing Across the Lifecourse"),
("Creative Audiovisual Coding"),
("Creative Audiovisual Coding B"),
("Creative Music Technologies"),
("Creative Practice: Ideas and Exploration"),
("Creative Practice: Producing and Curating"),
("Creative Research Methods for Design and Communication"),
("Creative Systems and Computational Art"),
("Creative Video"),
("Crime and Punishment"),
("Crimes against Humanity (Aut)"),
("Crimes of Violence"),
("Criminal Law 1"),
("Criminal Law 1 (Advanced)"),
("Criminal Law 2"),
("Criminal Law 2 (Advanced)"),
("Criminological Classics"),
("Criminological Futures"),
("Criminology"),
("Criminology Project"),
("Criminology Research Proposal"),
("Criminology in Theory and Perspective"),
("Crisis, Revolution, Modernity"),
("Critical Approaches 1"),
("Critical Approaches 2"),
("Critical Perspectives on Conflict and Violence"),
("Critical Perspectives on Terrorism"),
("Critical Reading and Writing for Criminologists"),
("Critical Reading and Writing for Sociologists"),
("Critical Theory and Performance"),
("Cryptography (L.6)"),
("Cryptography (L.7)"),
("Cultural and Historical Geographies"),
("Culture Across Space and Time"),
("Culture and Representation"),
("Culture and Representation (Elective pathway)"),
("Culture and the Everyday"),
("Culture and the Everyday E"),
("Culture, Race and Ethnicity"),
("Cultures of Colonialism"),
("Current Issues in Cognitive Science"),
("Current Themes in the Anthropology of Latin America"),
("Current Topics in Evolution, Behaviour and Conservation"),
("Curriculum Knowledge 1: Explorers and Investigators"),
("Curriculum Knowledge 2: Physical Philosophers"),
("Curriculum Knowledge 3: The World as a Stage"),
("Cybernetics and Neural Networks"),
("Data Analysis Techniques"),
("Data Analytics for Accounting & Finance"),
("Data Coding & Visualisation"),
("Data Structures & Algorithms"),
("Database and Application Development"),
("Databases"),
("Death of Socialism?"),
("Debates in Media Studies A"),
("Debates in Media Studies B"),
("Debates in Screen Documentary B"),
("Decolonial Movements"),
("Decolonisation, Pedagogy and Praxis in the Global South"),
("Democracy and Inequality"),
("Design Philosophy"),
("Design Project"),
("Design Project (BA)"),
("Design Techniques in Practice"),
("Design for Industry"),
("Design for Manufacture"),
("Design for Manufacture for Product Design"),
("Design of Clean Vehicle Propulsion"),
("Design of Mechanisms and Machines"),
("Developing Children's Communication, Language and Literacy"),
("Developing Leadership (LEAD)"),
("Developing Role Models: Peer-Led Mentoring in Schools"),
("Developing Your Research Proposal"),
("Development Tools and Skills"),
("Development and the State"),
("Development, Business and Corporate Social Responsibilities"),
("Development, Business and Corporate Social Responsibility"),
("Developmental Biology"),
("Developmental Psychology"),
("Differential Equations with Modelling"),
("Digital Arts Practice"),
("Digital Banking and FinTech"),
("Digital Communications"),
("Digital Cultures B"),
("Digital Development: Gender, Health and Technology"),
("Digital Environment"),
("Digital Histories, Objects and Processes"),
("Digital Marketing"),
("Digital Media Project Preparation"),
("Digital Media and Culture: Theories, Investigations, Practices"),
("Digital Methods Project"),
("Digital Music Cultures"),
("Digital Signal Processing"),
("Digital Signal Processing Laboratory"),
("Digital Systems and Microprocessor Design"),
("Digital, Data and Decision-Making Skills"),
("Digitalisation and Business Processes"),
("Dirty Wars? Conflict and Military Intervention"),
("Disasters, Environment and Development"),
("Discovering Role Models: Peer-Led Mentoring in Schools BACY"),
("Discovering Statistics"),
("Discrete Mathematics"),
("Dissertation"),
("Dissertation (ENGLISH)"),
("Dissertation (Digital Media and Culture)"),
("Documentary Video"),
("Doing Social Research: working with qualitative data"),
("Doing Social Research: working with quantitative data"),
("Drawing for Design"),
("Drugs, Brain and Behaviour"),
("Dynamical Systems"),
("Dynamics of Machines & Vehicles"),
("E-Business and E-Commerce Systems"),
("Early Modern Philosophy"),
("East Asia Rising: Beyond the American Century?"),
("Economic Perspectives on Development"),
("Economics and Data Science"),
("Economics of Crime"),
("Economics of Education"),
("Economics of European Integration"),
("Economics of Public Policy"),
("Economics of Sports"),
("Educating the Whole Child"),
("Education and Inequality"),
("Educational Psychology"),
("Electrical Circuits & Devices"),
("Electrical Drive Systems"),
("Electrical Machines & Power Electronics"),
("Electrical Power Systems"),
("Electricity and Electronics Laboratory"),
("Electricity and Magnetism"),
("Electrodynamics"),
("Electromagnetism and Introduction to Electrical Machines"),
("Electromechanics"),
("Electronic Circuit & Systems Design"),
("Electronic Devices and Circuit Prototyping"),
("Electronic Music Practice"),
("Electrons, Cold Atoms & Quantum Circuits"),
("Embedded Systems"),
("Embedding Professional Practice in Primary and Early Year Settings"),
("Empirical Finance Project"),
("Employment Law - Foundations"),
("Engaging Young Learners - Growing, Playing, Talking and Learning"),
("Engaging in Professional Practice in Primary and Early Year Settings"),
("Engineering Fluid Mechanics"),
("Engineering Mathematics 2"),
("Engineering Maths 1A"),
("Engineering Maths 1B"),
("Engineering Mechanics"),
("Engineering Scalable and Reliable Software Project"),
("Engineering Thermodynamics"),
("Engineering and Design Industrial Placement"),
("English Legal System"),
("English in the United States"),
("Enterprise in the Circular Economy"),
("Entrepreneurship"),
("Entrepreneurship Finance and Accounting (ENT)"),
("Entrepreneurship and Small Firms (ENT)"),
("Environmental Anthropology"),
("Environmental Economics"),
("Environmental Management and Sustainable Development"),
("Environmental Perspectives on Development"),
("Environmental Protest: Past and Present"),
("Environmental Research Skills (BSc Geog)"),
("Environmental Research Skills (E&C)"),
("Epistemology"),
("Equality, Diversity and Inclusion"),
("Equity & Trusts 1"),
("Equity & Trusts 2"),
("Ethics"),
("Ethics and Organisations: Responsibility and Justice"),
("Ethnographic Field Research"),
("Ethnographic Research Methods"),
("European Cinema"),
("European Politics"),
("Evaluating Special Educational Needs, Disability, Inclusion and Diversity"),
("Evolution, Behaviour and Ecology"),
("Evolutionary Biology"),
("Existentialism"),
("Experience Prototyping"),
("Experimental Biochemistry"),
("Experimental Economics: Markets, Games And Strategic Behaviour"),
("Explanatory Concepts in Political Science"),
("Exploring Children's Communication, Language and Literacy"),
("Exploring Film Studes B"),
("Exploring Film Studies"),
("Exploring Professional Practice in Primary and Early Year Setting"),
("Fashion Law"),
("Feminism and Digital Culture"),
("Feminism and Women's Political Activism in Britain"),
("Feminist Philosophy"),
("Field Biology and Conservation Skills"),
("Film Music Beyond Hollywood"),
("Film Music and Audiovisual Project"),
("Film Musicals"),
("Film Studies Dissertation"),
("Film Theory"),
("Film Theory B"),
("Film and Revolution"),
("FinTech Research Project"),
("Final Creative Project"),
("Final Creative Project - Documentary Video"),
("Final Year Performance Project"),
("Finance and Power"),
("Finance for Development"),
("Finance in Global Business"),
("Financial Derivatives"),
("Financial Econometrics"),
("Financial Economics"),
("Financial Institutions and Markets"),
("Financial Invest & Corp Risk Analysis"),
("Financial Mathematics (L.6)"),
("Financial Mathematics (L.7)"),
("Financial Portfolio Analysis"),
("Financial Risk Management"),
("Finite Element Analysis"),
("Fintech and Financial Transformation"),
("Forensic Linguistics"),
("Forensic Psychology"),
("Foundation Mathematics A"),
("Foundation Mathematics B"),
("Foundation Mechanics"),
("Foundation Programming"),
("Foundations in Psychology: Applied Psychology"),
("Foundations in Psychology: Health and Clinical A"),
("Foundations in Psychology: Health and Clinical B"),
("Foundations in Psychology: Social Psychology"),
("Foundations of Environmental Law"),
("Foundations of International Relations (pathway elective)"),
("Foundations of Politics"),
("French Ab initio A"),
("French Ab initio B"),
("French Advanced A"),
("French Advanced A (B)"),
("French Advanced B"),
("French Advanced B (B)"),
("French For Professional Purposes 1A"),
("French For Professional Purposes 1B"),
("French For Professional Purposes 3A"),
("French For Professional Purposes 3B"),
("French Intermediate A"),
("French Intermediate A Year 1"),
("French Intermediate B"),
("French Intermediate B Year 1"),
("French for Professional Purposes 2A"),
("French for Professional Purposes 2B"),
("French in Context A"),
("French in Context B"),
("From Decorative Arts to Material Culture"),
("From Opera to Film"),
("From Sounds to Words"),
("From Words to Interaction"),
("Frontiers in Particle Physics"),
("Functional Analysis (L.6)"),
("Functional Analysis (L.7)"),
("Functional Group Chemistry"),
("Fundamentals of Cancer Cell Biology"),
("Fundamentals of Machine Learning"),
("Fundamentals of Mathematics"),
("Further Mathematics A"),
("Further Mathematics B"),
("Further Programming"),
("Further Quantum Mechanics"),
("Galactic Astrophysics"),
("Galaxies and the Cosmos"),
("Game Design and Development"),
("Gender and Development: Theory, Concepts and Issues"),
("Gender, Crime and Justice"),
("Gender, Race and Society in Early Modern Drama"),
("Gender, Space and Culture"),
("Gendering the Life Course"),
("General Relativity"),
("Generative Arts and Musical Machines"),
("Genetics and Genomics"),
("Genetics and Population Genetics"),
("Genome Stability, Genetic Diseases and Cancer"),
("Genomics and Bioinformatics"),
("Geographical Information Systems"),
("Geographies of Money, Finance, and Debt"),
("Geographies of Rising and Declining Powers"),
("Geographies of Violence and Conflict"),
("Geography Overseas Field Class"),
("Geography Thesis"),
("Geography Thesis (BSc)"),
("Geohazards: Climate, Disasters and Sustainable Development"),
("German Ab initio A"),
("German Ab initio B"),
("German Advanced A"),
("German Advanced B"),
("German Intermediate A"),
("German Intermediate B"),
("German in Context A"),
("Global Business Law and Regulation (Spring)"),
("Global Business Organisation"),
("Global Childhoods"),
("Global Cinema"),
("Global Climate Change"),
("Global Cultures, Local Lives"),
("Global Design Challenge"),
("Global Development Challenges and Innovation"),
("Global Development Paradigms, Policy and Politics"),
("Global Economic History"),
("Global Environmental Change"),
("Global Food Security"),
("Global History from the Global South"),
("Global Humanities 1: Identities in a Global Context"),
("Global Humanities 2: Hope and Fear - Cultures, Climates, Ecologies"),
("Global Humanities 3: Values and Believing"),
("Global Humanities 4: Futures"),
("Global Innovation Systems"),
("Global Issues"),
("Global Issues: Researching the Global"),
("Global Landscape Dynamics"),
("Global Perspectives on Terrorism and Counter Terrorism A"),
("Global Perspectives on Terrorism and Counter Terrorism B"),
("Global Politics of Food"),
("Global Resistance: Subjects and Practices"),
("Global Strategy"),
("Globalisation and Communication"),
("Globalisation and Global Governance"),
("Globalisation and Integration"),
("Governing Technology"),
("Great Ideas about Language"),
("Haematology and Anatomy"),
("Hate Crime and the Law"),
("Health Psychology"),
("Health across the Lifecourse"),
("Health and Wellbeing"),
("Health, Poverty and Inequality"),
("Heat Transfer"),
("Heat Transfer Applications"),
("Historical Childhoods"),
("Historical Controversy"),
("Histories of Women in Music"),
("History Short Period: America in the 20th Century"),
("History Short Period: Britain in the 20th Century"),
("History Short Period: Europe in the 20th Century"),
("History Short Period: The Middle East and North Africa since 1908"),
("History Special Dissertation"),
("History Special Dissertation Israel - US Relations"),
("History Special Dissertation: Israel - US Relations and the New Diplomatic History"),
("History Special Dissertation: The Civil Rights Movement"),
("History Thematic Course: Awakenings"),
("History Thematic Course: Emotions"),
("History Thematic Course: The Enlightenment"),
("History and Practice of Songwriting"),
("History of English"),
("Hollywood Industry and Imaginary"),
("Horizontal Development(s)"),
("How Bodies Work"),
("Human Factors and Ergonomics"),
("Human Geographies of the Modern World"),
("Human Growth and Development"),
("Human Physiology"),
("Human Physiology and Metabolism"),
("Human Rights"),
("Human Rights 1: International and Regional Frameworks"),
("Human Rights 2: Critical Perspectives"),
("Human Rights, Security and Decoloniality"),
("Human-Computer Interaction"),
("Humans and Animals"),
("Ice Age Earth"),
("Ideas of History"),
("Identity and Interaction"),
("Identity, Violence and Transgression"),
("Image Processing"),
("Immigration & Asylum Law"),
("Immunology in Health and Disease"),
("Inclusive Childhoods"),
("Independent Research Project: Dissertation"),
("Independent Research Project: Practical"),
("Independent Research Project: Professional Work Experience"),
("Independent Study/Internship Option"),
("Indian Cinema: Popular Hindi Film"),
("Individual Project"),
("Individuals and Groups"),
("Industrial Automation Systems"),
("Industrial Dynamics"),
("Industry Projects"),
("Influence and Social Power (LEAD)"),
("Informatics Industrial Placement"),
("Information Systems"),
("Inner Worlds: Literature, 800-1750"),
("Innovation Systems"),
("Innovation in Bioscience and Medicine"),
("Institutions of Aid"),
("Instrumental Analysis"),
("Integrated Product Design: Research, Theory and Practice"),
("Integrated Reporting"),
("Intellectual Property: Copyright and Related Rights"),
("Intellectual Property: Industrial Property"),
("Intelligence in Animals and Machines"),
("Intelligent Systems Techniques"),
("Interaction Methods"),
("Interactive Design"),
("Interactive Music Systems"),
("Intermediate Fiction Filmmaking"),
("Intermediate Financial Accounting"),
("Intermediate Management Accounting"),
("International Business Environment"),
("International Business Strategy"),
("International Business Transactions"),
("International Development Thesis"),
("International Economic Disputes"),
("International Education and Development"),
("International Financial Management"),
("International Human Resource Management (HRM)"),
("International Marketing"),
("International Marketing (Marketing and Management)"),
("International Negotiations Management"),
("International Politics"),
("International Relations of the Modern Middle East"),
("International Trade"),
("International Trade Law"),
("Internet Law and Regulation"),
("Internet-of-Things and Embedded System Practice"),
("Introducing Media, Film and Music"),
("Introducing Social Pedagogy: Professional Approaches"),
("Introduction to Accounting"),
("Introduction to Accounting (Elective)"),
("Introduction to Accounting, Finance"),
("Introduction to Accounting, Management"),
("Introduction to American Studies"),
("Introduction to Astrophysics"),
("Introduction to Biomedicine"),
("Introduction to Business and Management"),
("Introduction to Business and Management (Elective)"),
("Introduction to Childhood and Youth: Interdisciplinary Perspectives"),
("Introduction to Computer Security"),
("Introduction to Computer Systems"),
("Introduction to Drug Design"),
("Introduction to Ecology and Conservation"),
("Introduction to Econometrics (level 5)"),
("Introduction to Economics"),
("Introduction to Economics for Accountants"),
("Introduction to English Legal System (Graduate Entry)"),
("Introduction to Entrepreneurship (ENT)"),
("Introduction to Evolution and Biodiversity"),
("Introduction to Fiction Filmmaking"),
("Introduction to Financial Accounting"),
("Introduction to Human Disease"),
("Introduction to International Political Economy"),
("Introduction to International Relations"),
("Introduction to Management Accounting"),
("Introduction to Marketing"),
("Introduction to Materials"),
("Introduction to Mathematical Biology"),
("Introduction to Mathematics for Finance and Economics"),
("Introduction to Metabolism and Pharmacology"),
("Introduction to Multimedia"),
("Introduction to Music Studies"),
("Introduction to Nano-materials and Nano-characterisation"),
("Introduction to Neuroscience"),
("Introduction to Organic Chemistry"),
("Introduction to Organometallic Chemistry"),
("Introduction to Probability"),
("Introduction to Product Design 1: Process"),
("Introduction to Product Design 2: Practice"),
("Introduction to Professional Learning and Development - Part One"),
("Introduction to Professional Learning and Development - Part Two"),
("Introduction to Programming"),
("Introduction to Quantum Physics"),
("Introduction to Statistics"),
("Introduction to Sustainable Development"),
("Introduction to the European Union"),
("Introductory Biology"),
("Introductory Chemistry"),
("Islam, Literature and the 'West'"),
("Islamic Philosophy"),
("Issues and Perspectives in Contemporary Performance"),
("Italian Ab initio A"),
("Italian Ab initio B"),
("Italian Advanced A"),
("Italian Advanced B"),
("Italian Intermediate A"),
("Italian Intermediate B"),
("Italian in Context A"),
("Italian in Context B"),
("Japanese Ab initio A"),
("Japanese Ab initio B"),
("Japanese Advanced A"),
("Japanese Advanced B"),
("Japanese Intermediate A"),
("Japanese Intermediate B"),
("Japanese in Context A"),
("Journalism Project"),
("Journalism Work Experience"),
("Journalism in Crisis B"),
("Journalism, Politics and Society"),
("Justice, Equality and Society"),
("Kant"),
("Key Concepts in Anthropology"),
("Key Debates in Contemporary Anthropology"),
("Key Thinkers in Development"),
("Knowledge & Reasoning"),
("Labour Economics"),
("Land Law 1"),
("Land Law 2"),
("Land, Property and Environment"),
("Language and Gender"),
("Language and Power"),
("Language in the Workplace"),
("Language, Mind and Brain"),
("Languages of the World"),
("Lasers and Photonics"),
("Law and Development"),
("Law and Resistance 1"),
("Law and the Entertainment Industry"),
("Law and the Welfare State"),
("Law for Accounting"),
("Law for Social Work"),
("Law of Business Organisations"),
("Law of Evidence"),
("Law of Succession (Spr)"),
("Law, Gender and Sexuality (Aut)"),
("Law, Regulation and Governance"),
("Law, Regulation and Governance B"),
("Leadership Foundations (LEAD)"),
("Leading Groups and Teams (LEAD)"),
("Legal Ethics and Professional Conduct"),
("Leveraging Human Capital and Performance (HRM)"),
("Life Science Bioscience Third Year Research Project"),
("Life Sciences MSci research project"),
("Life Sciences Master of Science Research Proposal"),
("Limits of Computation"),
("Linear Algebra 1"),
("Linear Algebra 2"),
("Linear Statistical Models"),
("Literature, Politics and Culture in Postwar Britain"),
("Lives of Carnivores"),
("Living Well: Modes of Self-Focus"),
("Local Lives: Identifying Global Studies"),
("Logic and Meaning"),
("Low Emission Vehicle Propulsion"),
("Lyric Poetry"),
("MEng Group Project"),
("MMath Project"),
("MPhys Final Year Project"),
("Machine Learning"),
("Macroeconomics 1"),
("Macroeconomics 2"),
("Making History A"),
("Making History B"),
("Making Music Theatre"),
("Making the Familiar Strange"),
("Management of Innovation"),
("Managing Change (HRM)"),
("Managing Digital Work"),
("Managing Global Supply Chains (OPS&IS)"),
("Managing Innovation"),
("Managing Operations"),
("Managing Projects and Technologies for Accounting and Marketing Students"),
("Managing Projects and Technologies for Business Students"),
("Manipulating Minds"),
("Marketing Analysis and Financial Strategic Planning"),
("Marketing Analytics and Metrics"),
("Marketing Communications"),
("Marketing Research"),
("Marketing Strategy"),
("Masters African Zoology Field Course"),
("Masters Mediterranean Ecology and Behaviour Field Course"),
("Masters Research Project (45 credits)"),
("Masters Tropical Rainforest Field Course"),
("Materials and Manufacturing Processes"),
("Materials and Processes for Product Design"),
("Mathematical Concepts"),
("Mathematical Fluid Mechanics (L6)"),
("Mathematical Fluid Mechanics (L7)"),
("Mathematical Methods for Physics 1"),
("Mathematical Methods for Physics 2"),
("Mathematical Methods for Physics 3"),
("Mathematical Models in Finance and Industry"),
("Mathematical Physics Projects"),
("Mathematical Research Project"),
("Mathematical Research Project Autumn"),
("Mathematical Statistics"),
("Mathematics and Computational Methods for Complex Systems"),
("Mathematics for Computing 1"),
("Mathematics for Computing 2"),
("Mathematics for Product Design"),
("Maths and Data Analysis for Chemists"),
("Measure and Integration (L.6)"),
("Measure and Integration (L.7)"),
("Mechanical Dynamics"),
("Mechanics and Properties of Matter Laboratory"),
("Mechanics and Relativity"),
("Mechanics of Mechanisms and Robots"),
("Media Law and Regulation"),
("Media and Communications Dissertation"),
("Media and Communications Dissertation Preparation"),
("Media and Political Violence in the 21st century: from managing perception to stopping revolution"),
("Media, Memory, History"),
("Media, War and Terrorism"),
("Medical Microbiology"),
("Medical Neuroscience"),
("Medicine and the Body"),
("Mediterranean Ecology and Behaviour Field Course"),
("Mediterranean Fantasies: Revivals and Utopias, 1919-1939"),
("Mercenaries, Gangs and Terrorists: Private Security in International Politics"),
("Metaphysics"),
("Methods and Approaches in Human Geography"),
("Microeconomics 1"),
("Microeconomics 2"),
("Migration and Integration (Spr)"),
("Migration, Identity, and Home"),
("Mind and Brain"),
("Mobile 3D Applications"),
("Mobile Communications"),
("Mobilities and Global Inequalities"),
("Modern America"),
("Modern European Philosophy"),
("Modern Inorganic Materials"),
("Modern Methods in Genetics"),
("Modern Political Thought"),
("Modern and Postmodern Drama"),
("Modernisms"),
("Molecular Biology"),
("Molecular Genetics"),
("Molecular Pharmacology"),
("Molecular Symmetry"),
("Monetary Theory and Policy"),
("Monte Carlo Simulations"),
("Morality, Groups and Emotion"),
("Music Dissertation"),
("Music Innovation and Enterprise Project"),
("Music Production"),
("Music and Society A"),
("Music of the 21st Century"),
("Musical Revolutions"),
("NGOs in World Politics"),
("Natural Language Engineering"),
("Nature and Nurture of Mental Health"),
("Neural Circuits"),
("Neural Networks"),
("Neurobiology of Brain Disorders"),
("Neurocriminology"),
("Neuronal Transduction and Transmission"),
("Neuroscience and Behaviour"),
("New Generation Vehicle Technology"),
("New Products Management"),
("New Venture Creation and Business Planning (ENT)"),
("New Venture Development and Planning"),
("News and Feature Writing"),
("News, Politics and Power A"),
("News, Politics and Power B"),
("Non-Profit Management and Social Entrepreneurship"),
("Novel Theory"),
("Nuclear and Particle Physics"),
("Number Theory"),
("Numerical Analysis"),
("Numerical Modelling and Engineering Simulations"),
("Numerical Solution of Partial Differential Equations (L.6)"),
("Numerical Solution of Partial Differential Equations (L.7)"),
("Online Journalism"),
("Operating Systems"),
("Operations Management"),
("Operations Management (Elective)"),
("Optics, Waves and Modern Physics"),
("Order and Disorder A: Understanding Law, Politics and Sociology"),
("Order and Disorder B: Understanding Law, Politics and Sociology"),
("Ordinary Differential Equations"),
("Organic Chemistry"),
("Organic Reaction Mechanisms"),
("Organisational Psychology"),
("Organometallic Chemistry and Catalysis"),
("Oscillations, Waves and Optics"),
("Outer Worlds: Literature, 800-1750"),
("Palaeozoology (Level 7)"),
("Palaeozoology of Dinosaurs and Megafauna"),
("Palestine and the International"),
("Parents and Families"),
("Partial Differential Equations"),
("Particle Physics"),
("Particle Physics Detector Technology"),
("Parties and Voters in the UK"),
("Past & Present: Beauty, Fashion and History"),
("Past and Present: Childhood and History"),
("Past and Present: Resistance and History"),
("Peer Relationships: From Toddlerhood to Middle Childhood"),
("Performance Workshop"),
("Performance: Directing and Composition"),
("Performing Practices"),
("Performing and Writing Music"),
("Performing with Electronics"),
("Permafrost and Environmental Change"),
("Perspectives on Healthcare Law"),
("Perspectives on Psychology"),
("Perturbation theory and calculus of variations"),
("Phases, Change and Rates"),
("Phenomenology"),
("Philosophical Foundations of Cognitive Science"),
("Philosophy and Science of Consciousness"),
("Philosophy of Language"),
("Philosophy of Mind"),
("Philosophy of Race & Racialisation"),
("Philosophy of Religion"),
("Philosophy of Science"),
("Phonology"),
("Photography: Critical Narratives"),
("Photography: Practice and Theory"),
("Photojournalism"),
("Physical Chemistry"),
("Physics Foundation Year Laboratory A"),
("Physics Foundation Year Laboratory B"),
("Physics Methods in Finance"),
("Physics Year 1 Laboratory"),
("Physics Year 2 Laboratory"),
("Physics in Practice"),
("Picasso to Kahlo: Transatlantic Dialogues"),
("Pidgins and Creoles"),
("Plant Physiology and Ecology"),
("Playable Media"),
("Podcasting"),
("Police and Policing"),
("Police and Policing (Elective)"),
("Policing Racial Capitalism"),
("Political Change: Contemporary France"),
("Political Change: Eastern Europe in Transition"),
("Political Change: Global Crisis and European Political Economy"),
("Political Change: India"),
("Political Change: Political Parties and Party Systems"),
("Political Change: Politics and International Business"),
("Political Change: The European Union as a Global Actor"),
("Political Change: The Rise of Anti-politics"),
("Political Change: the Politics of Brexit"),
("Political Corruption"),
("Political Ecology and Environmental Justice"),
("Political Economy of the Environment"),
("Political and Social Change in Contemporary Europe"),
("Politics and Power"),
("Politics of Governance: Eastern Europe"),
("Politics of Governance: France"),
("Politics of Governance: India"),
("Politics of Governance: International Institutions and Issues"),
("Politics of Governance: Ireland"),
("Politics of Governance: The European Union"),
("Politics of Governance: USA"),
("Politics of Terror and Global Histories of Violence"),
("Pop Life: After Modern Art"),
("Popular Music Cultures"),
("Positive Psychology"),
("Postcolonial Europe"),
("Posthuman/Premodern"),
("Power, Deviance and Othering"),
("Power, the State and the Individual"),
("Power, the State and the Individual (Advanced)"),
("Practical Quantum Technologies"),
("Practical Techniques in Cancer Cell Biology"),
("Practical Techniques in Cell and Molecular Biology"),
("Practice Learning 1"),
("Practice Learning 2"),
("Practicing Humanities 1: Analyse and Understand"),
("Practicing Humanities 2: Record and Present"),
("Practicing Humanities 3: Mobilise and Persuade"),
("Practicing Humanities 4: Evaluate and Reflect"),
("Practising Anthropology"),
("Practising Journalism"),
("Principles and Applications of Strength of Materials"),
("Principles of Banking"),
("Principles of Cognitive Science"),
("Principles of Finance"),
("Principles of Islamic Law"),
("Principles of Neuronal Function and Dysfunction"),
("Principles of Organisational Behaviour and Human Resource Management"),
("Principles of Public International Law"),
("Probability Models"),
("Probability and Statistics"),
("Professional Negligence"),
("Professional Placement Year"),
("Professional Placement Year (A&F)"),
("Professional Placement Year (Economics)"),
("Professional Placement Year (Type A)"),
("Professional Placement Year (Type B)"),
("Professional Placement Year Physics & Astronomy"),
("Professional Practice"),
("Professional Skills"),
("Professional and Managerial Skills"),
("Program Analysis"),
("Program Design"),
("Programming Concepts"),
("Programming for 3D"),
("Programming for Engineers"),
("Programming in C++"),
("Programming in Finance"),
("Programming through Python"),
("Project (FY Maths)"),
("Project Development - Documentary Video"),
("Project Development: Fiction"),
("Properties of Matter"),
("Protein Form and Function"),
("Psychobiology"),
("Psychological Perspectives on Self and Identity"),
("Psychology Now: Contemporary Approaches to Understanding Behaviour"),
("Psychology as a science"),
("Psychology of Appetite"),
("Psychology of Child Development"),
("Psychology of Childhood"),
("Psychology of Cognitive Processes"),
("Psychology of Crowds and Collective Action"),
("Psychology of Exercise and Wellbeing"),
("Psychology of Sleep"),
("Psychology of the Family: Beyond Attachment"),
("Public International Law in Current Affairs"),
("Public Law"),
("Public Law I: Constitutional and Administrative Law Advanced"),
("Public Management"),
("Public Relations"),
("Punishment and Penology"),
("Punishment and Penology (Spr)"),
("Putin, Power, Populism: Russia and Eurasia in Global Politics"),
("Quantitative Methods for Business and Economics: Maths"),
("Quantitative Methods for Business and Economics: Statistics"),
("Quantitative and Qualitative Methods"),
("Quantum Computing"),
("Quantum Field Theory 1"),
("Quantum Mechanics 1"),
("Quantum Mechanics 2"),
("Quantum Optics and Quantum Information"),
("Queer Literatures"),
("Questioning the Digital"),
("Questioning the Digital B"),
("Questioning the Media A"),
("Questioning the Media B"),
("Questioning the Media E"),
("Race and Ethnicity in Popular Cinema"),
("Race, Ethnicity and Identity"),
("Race, Ethnicity and Nationalism"),
("Race, Gender and Global Capitalism"),
("Radio to Optical Frequency Engineering"),
("Random processes (L.6)"),
("Random processes (L.7)"),
("Reaction Energetics and Kinetics"),
("Reactivity of the Elements"),
("Reading Art History: Critical Texts"),
("Reading Literature 1"),
("Reading Literature 2"),
("Reading Post-Colonial Texts"),
("Reading and Staging Theatre Texts"),
("Real Analysis"),
("Reason and Argument"),
("Reconfigurable System on Chip"),
("Reflecting on Professional Knowledge in Primary and Early Years Settings"),
("Refugees, Migrants and Religion"),
("Regulating Gene Expression"),
("Religion and Ritual"),
("Religions in Global Politics"),
("Representing Women"),
("Research Dissertation"),
("Research Dissertation (English Language)"),
("Research Foundations"),
("Research Methods (BA Social Work)"),
("Research Methods For Childhood and Youth"),
("Research Methods for Biology, Ecology and Zoology"),
("Research Methods for International Business"),
("Research Methods for Managers"),
("Research Methods for Neuroscience"),
("Research Methods in Biochemistry"),
("Research Methods in Genetics"),
("Research Minded Project"),
("Research Project"),
("Research Project (International Business)"),
("Research Project (Marketing and Management)"),
("Research Proposal (English Language)"),
("Research Skills and Methods in Political Science"),
("Research Skills for Development"),
("Researching Media and Communication"),
("Researching STEM"),
("Researching STEM for Life Sciences"),
("Researching, Creating and Communicating in the Humanities 1"),
("Researching, Creating and Communicating in the Humanities 2"),
("Resistance Movements in Conflict & War"),
("Restorative Justice and Desistance"),
("Revolutionary Media"),
("Rewilding and Ecosystem Services"),
("Rewriting the Canon"),
("Robot Design and Implementation"),
("Romance"),
("Romanticism"),
("Roots of America: From Colonial Settlement to the Civil War and Reconstruction"),
("School Placement Project"),
("Science and Literature"),
("Science and Reason"),
("Science of Memory"),
("Scientific Computing"),
("Scientific Scepticism and Critical Thinking"),
("Screenwriting"),
("Security and Insecurity in Global Politics"),
("Security and Insecurity in Global Politics (Pathway elective)"),
("Self Regulation: The Science of Achieving Your Goals"),
("Semantics"),
("Sense and Sexuality: Women and Writing in the Eighteenth Century"),
("Sensory Function and Computation"),
("Sequential Imaging"),
("Services Marketing"),
("Sexualities / Intimacies / Intersections"),
("Short Dissertation A"),
("Skills and Concepts in Geography I: Becoming a Geographer"),
("Skills and Concepts in Geography II: Quantitative and Analytical Skills"),
("Skills for Research Bioscientists"),
("Slavery, Emancipation and Legacies"),
("Smart Interactive Sensing Systems and Applications"),
("Social Change, Culture and Development"),
("Social Cognitive Development"),
("Social Enterprise and Social Innovation"),
("Social Geographies for a Post-Pandemic World"),
("Social Justice, Leadership & Organising: Practice"),
("Social Justice, Leadership & Organising: Theory"),
("Social Media and Critical Practice"),
("Social Media and Critical Practice B"),
("Social Psychology"),
("Social Psychology and Individual Differences"),
("Social Variation in English"),
("Social Work with Adults, their families and carers."),
("Social Work with Children, Young People and Families (BASW)"),
("Society, State and Humanity"),
("Sociology Project"),
("Sociology Research Proposal"),
("Sociology of Emotions and Mental Health"),
("Sociology of Fun (Aut)"),
("Sociology of Globalisation (Aut)"),
("Software Engineering"),
("Sonic Narratives"),
("Sound Design"),
("Sound for Interactive Media"),
("Sound, Culture & Society B"),
("Southeast England Field Class"),
("Spanish Ab initio A"),
("Spanish Ab initio B"),
("Spanish Advanced A"),
("Spanish Advanced A (B)"),
("Spanish Advanced B"),
("Spanish Advanced B (B)"),
("Spanish For Professional Purposes 3B"),
("Spanish Intermediate A"),
("Spanish Intermediate A Year 1"),
("Spanish Intermediate B"),
("Spanish Intermediate B Year 1"),
("Spanish for Professional Purposes 1A"),
("Spanish for Professional Purposes 1B"),
("Spanish for Professional Purposes 2A"),
("Spanish for Professional Purposes 2B"),
("Spanish for Professional Purposes 3A"),
("Spanish in Context A"),
("Spanish in Context B"),
("Special Author: Samuel Beckett"),
("Special Author: Virginia Woolf"),
("Special Author: William Blake"),
("Special Subject: Britain and the Second World War Part A"),
("Special Subject: Britain and the Second World War Part B"),
("Special Subject: End of Empire: Nationalism, Decolonisation and the British Raj in India 1937-1950 Part A"),
("Special Subject: End of Empire: Nationalism, Decolonisation and the British Raj in India 1937-1950 Part B"),
("Special Subject: Israel - US Relations and the New Diplomatic History Part B"),
("Special Subject: Israel - US Special Relations and the New Diplomatic History Part A"),
("Special Subject: Paying for the Past: Reparations and Restitution in Global Context Part A"),
("Special Subject: Paying for the Past: Reparations and Restitution in Global Context Part B"),
("Special Subject: Post-Rave Britain, 1988 - present Part A"),
("Special Subject: Post-Rave Britain, 1988 - present Part B"),
("Special Subject: The Civil Rights Movement"),
("Special Subject: The Civil Rights Movement Part A"),
("Special Subject: The Civil Rights Movement Part B"),
("Special Subject: Witches and Witch-Hunts Part A"),
("Special Subject: Witches and Witch-Hunts Part B"),
("Sports Law 1"),
("Sports Law 2"),
("Staging the Renaissance: Shakespeare"),
("Statistical Inference (L.6)"),
("Statistical Inference (L.7)"),
("Statistics Project"),
("Statistics and Decision Mathematics"),
("Statistics and Introductory Econometrics"),
("Stellar and Planetary Physics"),
("Stories of Art I: Shaping Art"),
("Stories of Art II: Who Is Art For?"),
("Strategic Brand Management"),
("Strategic Entrepreneurship"),
("Strategic Management - Engineering module"),
("Strategy"),
("Strategy in Organic Synthesis"),
("Strengthening Children's Mathematical Understanding"),
("Structural Basis of Biological Function"),
("Structure and Function in the Brain"),
("Structure, Bonding and the Periodic Table"),
("Studio Project"),
("Studio Recording"),
("Studio and Live Engineering"),
("Summer Research Placement 1"),
("Summer Research Placement 2"),
("Summer Research Placement 3"),
("Surface Analysis Techniques"),
("Surface Analysis Techniques e-learn"),
("Surveillance, Technology and Control"),
("Sussex Perspectives on International Development"),
("Sustainability in Engineering"),
("Symmetry in Particle Physics"),
("Synthetic Methods in Organic Chemistry"),
("Synthetic Methods in Organic Chemistry - E Learning"),
("Systems Analysis and Control"),
("TESOL 1A"),
("TESOL 1B"),
("TESOL 2A"),
("TESOL 2B"),
("TV: Fictions and Entertainments B"),
("Taxation"),
("Technical Drawing and Computer Aided Design"),
("Techniques in Neuroscience"),
("Technologies of Capture: Photography and Nineteenth Century Literature"),
("Technology-Enhanced Learning Environments"),
("The Anthropological Imagination"),
("The Anthropology of Exchange, Money and Markets"),
("The Anthropology of Geopolitics"),
("The Anthropology of Kinship and Relatedness"),
("The Anthropology of Work, Labour and Precarity"),
("The Art of Short Fiction"),
("The British Economy in the Twentieth Century"),
("The Cellular and Molecular Basis of Life"),
("The Changing World of Work"),
("The Chemistry of stable, unstable and non-existent inorganic compounds"),
("The Criminal Process"),
("The Cultural Life of Capital Punishment (Spr)"),
("The Early Modern World"),
("The Economics of Development"),
("The Far Right and the Politics of Immigration"),
("The Ghost in the Machine"),
("The Global Politics of Health"),
("The Golden State: Art in California, 1945-1981"),
("The History of Now"),
("The Idea of Classical Music"),
("The International System Today: Powers and Regions"),
("The Legal Regulation of Sexual Relationships"),
("The Liberal World Order - in Crisis"),
("The Local and the Global: IR in Practice"),
("The Look of America"),
("The Making of the Modern World"),
("The Narrative of Design in Modern Culture"),
("The Natural World"),
("The Novel"),
("The Order of Things: The Museum and its Objects"),
("The Politics of Armed Groups: Rebels, State and Society"),
("The Politics of Children's Literature"),
("The Politics of Feeling"),
("The Politics of Foreign Policy"),
("The Politics of Representation"),
("The Psychology of Inequality: From Poverty to Power"),
("The Purposes and Meanings of Education"),
("The Rise of the Modern International Order"),
("The Role of Design in the Circular Economy"),
("The Short Twentieth Century and Beyond"),
("The Single Market of the European Union"),
("The Single Market of the European Union (Advanced)"),
("The Sociology of Human Rights"),
("The global and the intimate: home cultures, belonging and personal life"),
("Theatre and Performance Analysis"),
("Themes and Perspectives in Sociology I"),
("Themes and Perspectives in Sociology II"),
("Themes in Analytic Philosophy"),
("Themes in Language, Truth and Literature"),
("Themes in Post-Kantian Philosophy"),
("Themes in Social and Political Philosophy"),
("Theoretical Concepts for American Studies"),
("Theoretical Physics"),
("Theories and Contexts of Drama"),
("Theorising Media Practice"),
("Theory Taste and Trash B"),
("Theory of Investments"),
("Therapeutic Work with Children and Young People (PA 3)"),
("Thermal and Statistical Physics"),
("Thinking Big: The 5 Senses"),
("Thinking Like a Criminologist"),
("Thinking Literature 1"),
("Thinking Literature 2"),
("Thinking Through Theatre"),
("Time and Place 1851: Science, Empire and Exhibitionism"),
("Time and Place: 1861: The Coming of the American Civil War"),
("Time and Place: 1942: Holocaust"),
("Time and Place: 1948: The Arab-Israeli Conflict"),
("Time and Place: 1953: Monarchs and Murders"),
("Time and Place: 1956: The Battle of Algiers"),
("Time and Place: 1984: Thatcher's Britain (Observing the 1980s)"),
("Topic(s) in American Literature and Culture"),
("Topics in Computer Science"),
("Topics in Growth and Inequality"),
("Topics in Wireless Communications"),
("Topics in the Philosophy of Cognitive Science"),
("Topology and Advanced Analysis (L6)"),
("Topology and Advanced Analysis (L7)"),
("Tort Law 1"),
("Tort Law 2"),
("Tort Law Advanced 1"),
("Tort Law Advanced 2"),
("Toy and Game Design"),
("Trade, (De)Globalisation, and the New Mercantilism"),
("Trading Strategies"),
("Transactional Banking Law"),
("Transcendence, Devotion and Desire"),
("Transnational Commercial Litigation"),
("Tropical Rainforest Science (Field trip Ecuador)"),
("Tropical Rainforests: Biogeography and Conservation"),
("Truth and Morality: The Meaning of Life"),
("Understanding Clinical Psychology"),
("Understanding Contemporary India"),
("Understanding Earth"),
("Understanding Global Migration"),
("Understanding Organisations, Management and Interprofessional Practice"),
("Understanding The African American Experience"),
("Understanding the Criminal Justice System"),
("Unpacking Children's Mathematical Understanding"),
("Urban Futures"),
("Urban Multiculture: Postcolonialism, Politics, Sound and the City"),
("Valuation of Companies and Cash Flow Generating Assets"),
("Values, Ethics and Theories: preparing for complexity in Social Work Practice"),
("Victims of Crime and Society (Aut)"),
("Victorian Visions: Art, Industry, Modernity"),
("Video Journalism"),
("Video Production Techniques"),
("Viewing Women"),
("Virology"),
("Visual Anthropology"),
("Visual Effects"),
("Voluntary Year Abroad - English Courses only"),
("War in International Politics"),
("Wealth, Inequality and Development"),
("Wearable Technologies"),
("Web 3D Applications"),
("Web Applications and Services"),
("What is War"),
("Whose Histories Matter? Doing Decolonial Heritage and National Identities"),
("Wollstonecraft and After: Gender, Writing and the Public Sphere"),
("Word & Image"),
("Worlds and Selves"),
("Writing Art History: Media, Society, Culture"),
("Writing Early America: Literature to 1800"),
("Writing Poetry"),
("Writing Race, Gender, and the Social: Experiments Beyond Representation"),
("Writing for Theatre"),
("Writing the New Nation: 1800-1900"),
("Writing the Short Film");